config/routes.rb
Rails.application.routes.draw do
  resources :visits 
  resources :members do
    get :birthdates, on: :collection
  end
  resources :leaders
  resources :events
  resources :payment_tests
  resources :menu_items


 
  resources :cities
  resources :states

  devise_for :users, path: "u"
  resources :users

  # token auth routes available at /api/auth
  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
    
    post 'special_periods/find_geolocation'   
    get 'settings/show'
    post 'utils/zipcode'
        
    resources :leaders, only: [:update, :show] do
      post :login, on: :collection
     # post :update, on: :member
      get :members, on: :member  
     
    end
 
    resources :cities, only: [:show] do
      post :find, on: :collection
      # post :find_states, on: :collection
      #post :find_by_state, on: :collection
      post :find_by_ibge, on: :collection
    end

    resources :members, only: [:create, :show, :update, :destroy] do      
      post :find_unvisited, on: :collection      
      post :find, on: :collection
      #post :create, on: :member
     # post :update, on: :member
      
    end

    resources :visits, only: [:create, :show] do      
      post :find_by_member, on: :collection 
      #post :create, on: :member
    end
    
  end

  resources :home, only: [:index]

  devise_scope :user do
    authenticated :user do
      root to: 'home#index'
      mount Crono::Web, at: '/crono'
    end

    unauthenticated do
      root to: 'devise/sessions#new'
    end
  end

  post 'utils/zipcode'
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include DeviseTokenAuth::Concerns::User

  rolify

  before_validation :assign_uid

  after_create :assign_role
  after_create :assign_generated_password

  

  belongs_to :userable, polymorphic: true, optional: true

  validates :email, presence: true, uniqueness: true
  has_one_attached :image, dependent: :destroy
  

  def address
    self.userable.address
  end

  

  def assign_role
    self.add_role(:basic) if self.roles.blank?
  end

  def assign_uid
    self.uid = self.email if self.uid.blank?
  end

  def assign_generated_password
    if self.encrypted_password.blank?
      self.generated_password = SecureRandom.hex
      self.password = self.generated_password
      self.save
    end
  end

  def image_urls
    self.image.map do |i|
      Rails.application.routes.url_helpers.rails_blob_path(i, only_path: true)
    end
  end
end 

app/controllers/users_controller.rb
class UsersController < Admin::ApplicationController
  load_and_authorize_resource

  # GET /users
  def index
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      @user.add_role :admin
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :salt, :encrypted_password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for object do |f| %>
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">
        <%= User.model_name.human %>
      </h3>
    </div>
    <div class="box-body">
      <div class="row">
        <%= f.input :name, wrapper_html: { class: 'col-md-3' } %>
        <%= f.input :email, wrapper_html: { class: 'col-md-3' } %>
        <%= f.input :password, wrapper_html: { class: 'col-md-3' } %>
      </div>
    </div>
  </div>

  <div class="box box-primary">
    <div class="box-footer">
      <%= link_to t('.back', default: t("helpers.links.back")), users_path, class: 'btn btn-default'  %>
      <%= f.submit  t('.save', default: t("helpers.links.save")), class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/_user_table.html.erb
<div class="row">
  <div class="col-md-9">
    <table class="table table-bordered table-striped">
      <tbody>           
        <tr>
          <th width='15%'><%= User.human_attribute_name(:name) %></th>
          <td><%= object.user.name %></td>
        </tr>
        <tr>
          <th width='15%'><%= User.human_attribute_name(:email) %></th>
          <td><%= object.user.email %></td>
        </tr>
        <tr>
          <th width='15%'><%= User.human_attribute_name(:address) %></th>
          <td><%= object.address.full_address %></td>
        </tr>
         
      </tbody>
    </table>
  </div>
  <div class="col-md-3 text-center">
    <% if object.user.image.attached? %>
      <%= image_tag object.user.image, class: 'img-responsive center-block', style: 'height: 120px' %>
    <% else %>
      Sem Imagem    
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form', object: @user %>

app/views/users/index.html.erb
<%= render 'shared/index', list: @users, show_columns: ['id', 'name', 'email', 'userable_type',
  'provider', 'sign_in_count', 'current_sign_in_at', 'current_sign_in_ip', 'last_sign_in_at', 'last_sign_in_ip'] do %>
  <% if can? :create, User %>
    <%= link_to new_user_path, class: 'btn btn-xs btn-primary' do %>
      <i class="fa fa-plus"></i> Cadastrar Usuário
    <% end %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<%= render 'form', object: @user %>

app/views/users/show.html.erb
<%= render 'shared/show', object: @user %>