config/routes.rb
Rails.application.routes.draw do
  resources :visits 
  resources :members do
    get :birthdates, on: :collection
  end
  resources :leaders
  resources :events
  resources :payment_tests
  resources :menu_items


 
  resources :cities
  resources :states

  devise_for :users, path: "u"
  resources :users

  # token auth routes available at /api/auth
  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
    
    post 'special_periods/find_geolocation'   
    get 'settings/show'
    post 'utils/zipcode'
        
    resources :leaders, only: [:update, :show] do
      post :login, on: :collection
     # post :update, on: :member
      get :members, on: :member  
     
    end
 
    resources :cities, only: [:show] do
      post :find, on: :collection
      # post :find_states, on: :collection
      #post :find_by_state, on: :collection
      post :find_by_ibge, on: :collection
    end

    resources :members, only: [:create, :show, :update, :destroy] do      
      post :find_unvisited, on: :collection      
      post :find, on: :collection
      #post :create, on: :member
     # post :update, on: :member
      
    end

    resources :visits, only: [:create, :show] do      
      post :find_by_member, on: :collection 
      #post :create, on: :member
    end
    
  end

  resources :home, only: [:index]

  devise_scope :user do
    authenticated :user do
      root to: 'home#index'
      mount Crono::Web, at: '/crono'
    end

    unauthenticated do
      root to: 'devise/sessions#new'
    end
  end

  post 'utils/zipcode'
  
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :eventable, polymorphic: true, optional: true, dependent: :destroy
  
  belongs_to :user

  monetize :value_cents, allow_nil: true

  after_create :create_eventable

  def create_eventable
    unless eventable
      ev = Kernel.const_get(self.eventable_type).new(
        start_date: start_date,
        final_date: final_date,
        user: user,
        accommodation: accommodation,
        event: self
      )
      ev.name = name if Kernel.const_get(self.eventable_type).column_names.include? 'name'
      ev.value = value if Kernel.const_get(self.eventable_type).column_names.include? 'value_cents'
      ev.save
      self.eventable_id = ev.id
      self.save
    end
  end

  def as_json(options = {})
    json_to_return = super(except: [ 'eventable_type', 'eventable_id',
      'value_cents', 'value_currency', 'created_at', 'updated_at'])
    json_to_return[:value] = ActionController::Base.helpers.number_to_currency(value) if value_cents
    json_to_return[:start] = start_date
    json_to_return[:end] = final_date + 1.day
    # json_to_return[:url] = '#'
    json_to_return[:allDay] = true
    # json_to_return[:rendering] = 'background'
    json_to_return[:extendedProps] = {}
    json_to_return[:extendedProps][:kind] = case eventable_type
      when 'Reserve'
        'Reserva'
      when 'Unavailability'
        'Indisponibilidade'
      when 'SpecialPeriod'
        'Período Especial'
      else
        'Evento'
    end
    json_to_return[:title] = case eventable_type
      when 'Reserve'
        'Reserva'
      when 'Unavailability'
        'indisponível'
      when 'SpecialPeriod'
        "#{name.blank? ? 'período especial' : name}: #{ActionController::Base.helpers.number_to_currency(value)}"
      else
        'gray'
    end
    json_to_return[:color] = case eventable_type
      when 'Reserve'
        'green'
      when 'Unavailability'
        'red'
      when 'SpecialPeriod'
        'blue'
      else
        'gray'
    end
    return json_to_return
  end
end

app/controllers/events_controller.rb
class EventsController < Admin::ApplicationController
  load_and_authorize_resource

  # GET /events
  def index
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)
    @event.user = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Evento cadastrado com sucesso.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Evento apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:name, :start_date, :final_date, :value, 
        :eventable_type, :accommodation_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_fields.html.erb
<div class="row">
  <%= f.input :eventable_type, label: 'Tipo',
    as: :select, collection: [
      [ 'Indisponibilidade', 'Unavailability' ],
      [ 'Período Especial', 'SpecialPeriod' ]
    ],
    input_html: { class: 'sselect2' }, wrapper_html: { class: 'col-md-4' } %>
  <%= f.input :start_date, html5: true, wrapper_html: { class: 'col-md-4' } %>
  <%= f.input :final_date, html5: true, wrapper_html: { class: 'col-md-4' } %>
  <%= f.input :name, wrapper_html: { class: 'col-md-6', style: "display: none" } %>
  <%= f.input :value, input_html: { class: 'currency' }, wrapper_html: { class: 'col-md-6', style: "display: none" } %>

  <%= f.input :accommodation_id, as: :hidden, wrapper_html: { class: 'col-md-4' } %>
</div>

app/views/events/_form.html.erb
<%= simple_form_for object do |f| %>
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">
        <%= Event.model_name.human %>
      </h3>
    </div>
    <div class="box-body">
      <%= render 'events/fields', f: f %>
    </div>
  </div>

  <div class="box box-primary">
    <div class="box-footer">
      <%= link_to t('.back', default: t("helpers.links.back")), events_path, class: 'btn btn-default'  %>
      <%= f.submit  t('.save', default: t("helpers.links.save")), class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= render 'form', object: @event %>

app/views/events/index.html.erb
<%= render 'shared/index', list: @events %>

app/views/events/new.html.erb
<%= render 'form', object: @event %>

app/views/events/show.html.erb
<%= render 'shared/show', object: @event %>