config/routes.rb
Rails.application.routes.draw do
  resources :visits 
  resources :members do
    get :birthdates, on: :collection
  end
  resources :leaders
  resources :events
  resources :payment_tests
  resources :menu_items


 
  resources :cities
  resources :states

  devise_for :users, path: "u"
  resources :users

  # token auth routes available at /api/auth
  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
    
    post 'special_periods/find_geolocation'   
    get 'settings/show'
    post 'utils/zipcode'
        
    resources :leaders, only: [:update, :show] do
      post :login, on: :collection
     # post :update, on: :member
      get :members, on: :member  
     
    end
 
    resources :cities, only: [:show] do
      post :find, on: :collection
      # post :find_states, on: :collection
      #post :find_by_state, on: :collection
      post :find_by_ibge, on: :collection
    end

    resources :members, only: [:create, :show, :update, :destroy] do      
      post :find_unvisited, on: :collection      
      post :find, on: :collection
      #post :create, on: :member
     # post :update, on: :member
      
    end

    resources :visits, only: [:create, :show] do      
      post :find_by_member, on: :collection 
      #post :create, on: :member
    end
    
  end

  resources :home, only: [:index]

  devise_scope :user do
    authenticated :user do
      root to: 'home#index'
      mount Crono::Web, at: '/crono'
    end

    unauthenticated do
      root to: 'devise/sessions#new'
    end
  end

  post 'utils/zipcode'
  
end

app/models/member.rb
class Member < ApplicationRecord
  include TranslateEnum

  enum status: {
    visited: 0,    
    unvisited: 1   
  }
  translate_enum :status
  
  belongs_to :leader
  has_one :address, dependent: :destroy, as: :addressable
  has_many :visits, dependent: :destroy

    
  accepts_nested_attributes_for :address, allow_destroy: true
  accepts_nested_attributes_for :visits, allow_destroy: true

  

  geocoded_by :geo_address

 after_validation :geocode



def geo_address
  address&.geo_address
end

def leader_name
 self.leader.name
end

def translate_status
  self.human_enum_name(:status, self.status)
end

def birthdate_br
  
end  


def member_json
  self.to_json(
    methods: [:translate_status, :birthdate_br],
    except: [:created_at, :updated_at, :leader_id],
    include: [ 
        leader:{
          methods: [:name],
          except:[ :created_at, :updated_at, :mother_name, :father_name, :user_id, :rg, :cpf, :latitude, :longitude]
           
        },
        address: {
          include:[
              city:{
                methods: [:name_with_state],
                only: [:id]
              }
            ],
          except:[:city_id, :addressable_type, :addressable_id, :created_at, :updated_at] 
        }
  ])
end





end

app/controllers/api/members_controller.rb
class Api::MembersController < Api::ApplicationController
    #load_and_authorize_resource

def find_unvisited
   
  @members  = {}
         
    if params[:latitude] && params[:longitude]      
      if params[:radius]
        @members = Member.near([params[:latitude].to_f, params[:longitude].to_f], params[:radius].to_f, unit: :km)
      else
        @members = Member.near([params[:latitude].to_f, params[:longitude].to_f])
      end          
    end

    @members = @members.where(leader_id: params[:id])

    if @members.any?
      @members = @members.where(status: "unvisited")
    end
    render json: {
      success: @members.any?,
      message: "#{@members.to_a&.size} membros encontrados",
      collection: @members.as_json(
        methods: [:translate_status, :birthdate_br],
        except: [:created_at, :updated_at, :leader_id],
        include: [ 
            leader:{
              methods: [:name],
              except:[ :created_at, :updated_at, :mother_name, :father_name, :user_id, :rg, :cpf, :latitude, :longitude]
               
            },
            address: {
              include:[
                city:{
                  methods: [:name_with_state],
                  only: [:id]
                }
              ],
              except:[:city_id, :addressable_type, :addressable_id, :created_at, :updated_at] 
            }
      ])
    }
  end

  def show
    @member = {}
    @member = Member.find_by(id: params[:id])
    if @member
      render json:  @member.member_json
    else
      render json:  {
        status: :not_found
      }
    end
  end

  def find
   
    @members  = {}
         
    if params[:latitude] && params[:longitude]      
      if params[:radius]
        @members = Member.near([params[:latitude].to_f, params[:longitude].to_f], params[:radius].to_f, unit: :km)
      else
        @members = Member.near([params[:latitude].to_f, params[:longitude].to_f])
      end          
    end

   @members = @members.where(leader_id: params[:id])
  
    render json: {
      success: @members.any?,
      message: "#{@members.to_a&.size} membros encontrados",
      collection: @members.as_json(
        methods: [:translate_status, :birthdate_br],
        except: [:created_at, :updated_at],
        include: [ 
            leader:{
              methods: [:name],
              except:[ :created_at, :updated_at, :mother_name, :father_name, :user_id, :rg, :cpf, :latitude, :longitude]
               
            },
            address: {
              include:[
                city:{
                  methods: [:name_with_state],
                  only: [:id]
                }
              ],
              except:[:city_id, :addressable_type, :addressable_id, :created_at, :updated_at] 
            }
      ])
    }
  end

  def create   
    @member = Member.new(member_params)  
    @member.status = "unvisited"
    if @member.save
      render json: @member.member_json, status: :created
    else
      render json:  {
        message: @member.errors.full_messages,
        member: @member.member_json,
        status: :unprocessable_entity
      }
    end
  end

     # POST /api/members/1
     def update
      @member = Member.find params[:id]
      if @member.update(member_params)
        render json: @member.member_json
      else
        render json:{
          message: @member.errors.full_messages,
          status: :unprocessable_entity
        }
      end
    end

    # DELETE /member/1
  def destroy
    @member = Member.find params[:id]
    if @member.destroy
      render json:  {        
        status: :ok
      }
    else
      render json:  {
        message: @member.errors.full_messages,
        status: :unprocessable_entity
      }
    end        
  end


  private
  def member_params 
    params[:member][:address_attributes] = params[:member][:address]
    params.fetch(:member).permit(:name, :cpf, :birthdate, :leader_id, :phone, :cell_phone,    
      address_attributes: [
        :id, :_destroy, :description, :zipcode, :street, :number, :complement, :district, :city_id
      ],
      visits_attributes: [
          :id, :_destroy, :date_visit, :observation, :number_of_voters
        ]
    )
    
    
   
  end

  

end

app/controllers/members_controller.rb
class MembersController  < Admin::ApplicationController
  load_and_authorize_resource

  # GET /member
  def index   
   @q = Member.ransack(params[:q])
   @members = @q.result.page(params[:page]).per 10
  end


  # GET /members/1  
  def show
  end

  def birthdates
    @q = Member.ransack(params[:q])
    @mes = Date.today.month

    if params[:date]
      @mes = params[:date][:month]
    end  

    @birthdays_of_month = Member.where('extract(month from birthdate) = ?', @mes).order('birthdate DESC')
   
   
  end
    


  # GET /members/new
  def new
    @member = Member.new
    @member.build_address
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  def create
    @member = Member.new(member_params)
    @member.status = "unvisited"
    if @member.save
      redirect_to @member, notice: 'Member was successfully created.' 
    else
      render :new
    end
  end

  # PATCH/PUT /members/1
  def update
    if @member.update(member_params)
      redirect_to @member, notice: 'Member was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /member/1
  def destroy
    @member.destroy
    redirect_to members_url, notice: 'Member was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def member_params
      params.require(:member).permit(:name, :leader_id, :birthdate, :cpf, :status, :phone, :cell_phone, :date_month, :observation,
          
          address_attributes: [
            :id, :_destroy, :description, :zipcode, :street, :number, :complement,
            :district, :city_id
          ],
          visits_attributes: [
            :id, :_destroy, :date_visit, :observation, :number_of_voters
          ]      
      )

    end

   
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= simple_form_for object do |f| %>
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">
        <%= Member.model_name.human %>
      </h3>
    </div>
    <div class="box-body">
     
        <div class="row user nested-fields">
        <div class = 'col-md-8' >
          <div class="row">
              <%= f.input :name, wrapper_html: { class: 'col-md-4' } %>
              <%= f.input :cpf, input_html: {id: "cpf"}, wrapper_html: { class: 'col-md-4' } %> 
              <%= f.input :phone, input_html: {id: "phone"}, wrapper_html: { class: 'col-md-4' } %> 
              <%= f.input :cell_phone, input_html: {id: "cell_phone"}, wrapper_html: { class: 'col-md-4' } %> 
              <%= f.input :birthdate, as: :date, html5: true, start_year: Date.today.year - 90,
                                      end_year: Date.today.year - 16, 
                                      order: [:day, :month, :year], wrapper_html: { class: 'col-md-4' } %>     
              <%= f.association :leader, wrapper_html: { class: 'col-lg-4' },
                collection: Leader.all, include_blank: false
              %>
              <%= f.input :observation, wrapper_html: { class: 'col-md-4' } %> 
          
          </div>
        </div>
       
    </div>
      
    </div>
  </div>
  

  <%= f.simple_fields_for :address do |address| %>
    <%= render 'shared/address_fields', f: address %>
  <% end %> 

   
   <div class="row user nested-fields">
    <div class="tab-pane" id="tab_2">
      
    </div>
   </div>  

  <div class="box box-primary">
    <div class="box-footer">
      <%= link_to t('.back', default: t("helpers.links.back")), members_path, class: 'btn btn-default'  %>
      <%= f.submit  t('.save', default: t("helpers.links.save")), class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/members/_month.html.erb
<div class="row user nested-fields">
  <div class = 'col-md-8' >
    <div class="row">
    <%= select_month(@months) %>      
    </div>
  </div>
  
</div>

app/views/members/birthdates.html.erb
<%= form_tag(birthdates_members_path, method: :get, id: "month") do %>
  
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">
        Mês
      </h3>
    </div>
    <div class="box-body">
      <div class="row">
        <%= label_tag(:month, "Buscar Por:") %>
         <%= select_month(@mes.to_i) %>  
         <%= submit_tag 'buscar' %>           
      </div>
    </div>
  </div>


<% end %>


<%= render 'shared/index',
  list: @birthdays_of_month,
  show_columns: [
    'id', 'name','birthdate', 'leader_name', 'translate_status', 'address.district', 'address.city.name_with_state', 'phone', 'cell_phone'
  ]
%>

app/views/members/edit.html.erb
<%= render 'form', object: @member %>

app/views/members/index.html.erb
<%= render 'shared/index',
  list: @members,
  show_columns: [
    'id', 'name','cpf', 'leader_name', 'translate_status', 'address.district', 'address.city.name_with_state', 'phone', 'cell_phone'
  ],
  sort_fields: ['name'],
  search_fields: [
    { field: 'name_cont', label: 'Nome do Membro' } 
  ]
%>

app/views/members/new.html.erb
<%= render 'form', object: @member %>

app/views/members/show.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">
      Dados do Membro
      <% if can? :new, Member %>
        <%= link_to members_path, class: "btn btn-primary btn-xs", data: { toggle: 'tooltip', placement: 'top', title: 'Cadastrar' } do %>
          Cadastrar <i class="fa fa-plus"></i>
        <% end %>
      <% end %>
      <% if can? :edit, @member %>
        <%= link_to edit_member_path(@member), class: "btn btn-warning btn-xs", data: { toggle: 'tooltip', placement: 'top', title: 'Editar' } do %>
          Editar <i class="fa fa-pencil"></i>
        <% end %>
      <% end %>
      <%= link_to 'Listagem', members_path, class: "btn btn-default btn-xs" %>
    </h3>
  </div>
  
  <div class="box-body no-padding">
    <div class="row">
      <div class="col-md-9">
        <table class="table table-bordered table-striped">
          <tbody>           
            <tr>
              <th width='15%'><%= Member.human_attribute_name(:name) %></th>
              <td><%= @member.name %></td>
            </tr>
            <tr>
              <th width='15%'><%= Member.human_attribute_name(:cpf) %></th>
              <td><%= @member.cpf %></td>
            </tr>
            <tr>
              <th width='15%'><%= Member.human_attribute_name(:birthdate) %></th>
              <td><%= @member.birthdate %></td>
            </tr>
            <tr>
              <th width='15%'><%= Member.human_attribute_name(:address) %></th>
              <td><%= @member.address.full_address %></td>
            </tr>
            <tr>
              <th width='15%'><%= Member.human_attribute_name(:leader) %></th>
              <td><%= @member.leader.name %></td>
            </tr>
            <tr>
              <th width='15%'><%= Member.human_attribute_name(:status) %></th>
              <td><%= @member.translate_status %></td>
            </tr>
            <tr>
              <th width='15%'><%= Member.human_attribute_name(:latitude) %></th>
              <td><%= @member.latitude %></td>
            </tr>
            <tr>
              <th width='15%'><%= Member.human_attribute_name(:longitude) %></th>
              <td><%= @member.longitude %></td>
            </tr>
            <tr>
              <th width='15%'><%= Member.human_attribute_name(:phone) %></th>
              <td><%= @member.phone %></td>
            </tr>
            <tr>
              <th width='15%'><%= Member.human_attribute_name(:cell_phone) %></th>
              <td><%= @member.cell_phone %></td>
            </tr>
            <tr>
              <th width='15%'><%= Member.human_attribute_name(:observation) %></th>
              <td><%= @member.observation %></td>
            </tr>
          </tbody>
        </table>
      </div>
      
    </div>
  </div>
  
</div>

<%= render 'shared/index', list: @member.visits,
  show_columns: [    
    'date_visit', 'observation', 'number_of_voters'
  ], 
  hide_links: true
%>